package shared;

public enum MessageType {
    CREATE_ROOM, JOIN_ROOM, ROOM_JOINED, ROOM_ERROR, ROOM_SETTINGS,
    START_GAME, DRAW_PROMPT, SELECTED_WORD, CHAT_MESSAGE,
    GUESS, CORRECT_GUESS, SCORE_UPDATE, NEXT_TURN, GAME_OVER,
    PLAYER_JOINED, PLAYER_LEFT, DRAW_DATA
}